In [1]:
import onnx_graphsurgeon as gs
import onnx
import numpy as np
import sys
sys.path.append("..")
import onnx_utils
import add_rewrite

In [2]:
graph = gs.import_onnx(onnx.load("/home/yssun/onnx/enode/test_model/model_identity.onnx"))

In [3]:
tmp = graph.tensors()

In [4]:
tmp

OrderedDict([('input', Variable (input): (shape=[1024, 22], dtype=int64)),
             ('onnx_graphsurgeon_constant_0',
              Constant (onnx_graphsurgeon_constant_0): (shape=[1024, 22], dtype=int64)
              LazyValues (shape=[1024, 22], dtype=int64)),
             ('add_out_gs_1',
              Variable (add_out_gs_1): (shape=[1024, 22], dtype=int64)),
             ('identy_out_gs_3',
              Variable (identy_out_gs_3): (shape=[1024, 22], dtype=int64))])

In [5]:
tmp['add_out_gs_1']

Variable (add_out_gs_1): (shape=[1024, 22], dtype=int64)

In [6]:
tmp['add_out_gs_1'].inputs

[onnx_graphsurgeon_node_2 (Add)
 	Inputs: [
 		Variable (input): (shape=[1024, 22], dtype=int64)
 		Constant (onnx_graphsurgeon_constant_0): (shape=[1024, 22], dtype=int64)
 	]
 	Outputs: [
 		Variable (add_out_gs_1): (shape=[1024, 22], dtype=int64)
 	]]

In [3]:
graph.nodes

[onnx_graphsurgeon_node_2 (Add)
 	Inputs: [
 		Variable (input): (shape=[1024, 22], dtype=int64)
 		Constant (onnx_graphsurgeon_constant_0): (shape=[1024, 22], dtype=int64)
 	]
 	Outputs: [
 		Variable (add_out_gs_1): (shape=[1024, 22], dtype=int64)
 	],
 onnx_graphsurgeon_node_4 (Identity)
 	Inputs: [
 		Variable (add_out_gs_1): (shape=[1024, 22], dtype=int64)
 	]
 	Outputs: [
 		Variable (identy_out_gs_3): (shape=[1024, 22], dtype=int64)
 	]]

In [9]:
outputs = graph.nodes[0].outputs

In [11]:
outputs[0].inputs

[onnx_graphsurgeon_node_2 (Add)
 	Inputs: [
 		Variable (input): (shape=[1024, 22], dtype=int64)
 		Constant (onnx_graphsurgeon_constant_0): (shape=[1024, 22], dtype=int64)
 	]
 	Outputs: [
 		Variable (add_out_gs_1): (shape=[1024, 22], dtype=int64)
 	]]

In [6]:
for o in outputs:
  o.inputs.clear()

In [5]:
addNode = graph.nodes[0]

In [6]:
addNode.inputs

[Variable (input): (shape=[1024, 22], dtype=int64),
 Constant (onnx_graphsurgeon_constant_0): (shape=[1024, 22], dtype=int64)
 LazyValues (shape=[1024, 22], dtype=int64)]

In [7]:
addVarInput = addNode.inputs[0]
addConstInput = addNode.inputs[1]

In [8]:
reop = graph.addRedencyRewrite(addVarInput,addNode,addConstInput,
                               12,22,0,12)

In [9]:
reop.inputs

[onnx_graphsurgeon_node_11 (Concat)
 	Inputs: [
 		Variable (tile_out_gs_9): (shape=None, dtype=None)
 		Variable (onnx_graphsurgeon_node_2/unAdd:0_1): (shape=None, dtype=None)
 	]
 	Outputs: [
 		Variable (add_out_gs_1): (shape=[1024, 22], dtype=int64)
 	]
 Attributes: {'axis': 1}]

In [10]:
reop.outputs

[onnx_graphsurgeon_node_4 (Identity)
 	Inputs: [
 		Variable (add_out_gs_1): (shape=[1024, 22], dtype=int64)
 	]
 	Outputs: [
 		Variable (identy_out_gs_3): (shape=[1024, 22], dtype=int64)
 	]]

In [11]:
graph.cleanup()


[W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored
[E] Function: '_ipython_canary_method_should_not_exist_' was not registered for opset 13. 
[W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored
[E] Function: '_ipython_display_' was not registered for opset 13. 
[W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored
[E] Function: '_ipython_canary_method_should_not_exist_' was not registered for opset 13. 
[W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored
[E] Function: '_repr_mimebundle_' was not registered for opset 13. 
[W] colored module is not installed, will not use colors when 

Graph onnx_graphsurgeon_graph (Opset 13)
Local Functions: []
Inputs: [Variable (input): (shape=[1024, 22], dtype=int64)]
Nodes: onnx_graphsurgeon_node_4 (Identity)
	Inputs: [
		Variable (add_out_gs_1): (shape=[1024, 22], dtype=int64)
	]
	Outputs: [
		Variable (identy_out_gs_3): (shape=[1024, 22], dtype=int64)
	]
onnx_graphsurgeon_node_2/unSlice (Slice)
	Inputs: [
		Variable (input): (shape=[1024, 22], dtype=int64)
		Constant (onnx_graphsurgeon_node_2/unSlice_value:0): (shape=(1,), dtype=int64)
		Constant (onnx_graphsurgeon_node_2/unSlice_value:1): (shape=(1,), dtype=int64)
		Constant (onnx_graphsurgeon_node_2/unSlice_value:2): (shape=(1,), dtype=int64)
	]
	Outputs: [
		Variable (onnx_graphsurgeon_node_2/unSlice:0_0): (shape=None, dtype=None)
	]
onnx_graphsurgeon_node_2/unAdd (Add)
	Inputs: [
		Variable (onnx_graphsurgeon_node_2/unSlice:0_0): (shape=None, dtype=None)
		Constant (onnx_graphsurgeon_node_2/unAdd_value:0): (shape=(1024, 10), dtype=int64)
	]
	Outputs: [
		Variable (onnx_grap

In [10]:
graph.outputs.append(reop)

In [9]:
for out in graph.outputs:
    out.dtype = np.int64

In [12]:
model = gs.export_onnx(graph)


In [13]:
onnx.save(model, "../test_model/re_model_identity1.onnx")

In [14]:
from onnxruntime import SessionOptions,ExecutionMode
import onnxruntime as ort
sess_opt = SessionOptions()
sess_opt.execution_mode  = ExecutionMode.ORT_PARALLEL
# sess_opt.inter_op_num_threads = 3
session = ort.InferenceSession("../test_model/re_model_identity1.onnx",sess_options = sess_opt,providers=[ 'CPUExecutionProvider'])
for i in range(10):
  random_input1 = np.random.rand(1024,22).astype(np.int64)
  out = session.run([],{"input":random_input1})

In [13]:
out

[array([[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]], dtype=int64),
 array([[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]], dtype=int64)]

In [19]:
x = np.random.randint(0, 100, size=(1024, 22), dtype=np.int64)


In [20]:
x[:, 0:12] = x[0, 0:12]


In [21]:
x

array([[95,  5, 19, ..., 62, 32, 69],
       [95,  5, 19, ..., 32, 88, 35],
       [95,  5, 19, ..., 57, 27, 10],
       ...,
       [95,  5, 19, ..., 45, 27, 96],
       [95,  5, 19, ..., 58,  5, 57],
       [95,  5, 19, ..., 42, 52, 72]])

In [22]:
out = session.run([],{"input":x})

In [23]:
out

[array([[96,  6, 20, ..., 63, 33, 70],
        [96,  6, 20, ..., 33, 89, 36],
        [96,  6, 20, ..., 58, 28, 11],
        ...,
        [96,  6, 20, ..., 46, 28, 97],
        [96,  6, 20, ..., 59,  6, 58],
        [96,  6, 20, ..., 43, 53, 73]], dtype=int64)]

In [24]:
session2 = ort.InferenceSession("../test_model/re_model_identity.onnx",sess_options = sess_opt,providers=[ 'CPUExecutionProvider'])
out2 = session2.run([],{"input":x})

In [25]:
out2

[array([[96,  6, 20, ..., 63, 33, 70],
        [96,  6, 20, ..., 33, 89, 36],
        [96,  6, 20, ..., 58, 28, 11],
        ...,
        [96,  6, 20, ..., 46, 28, 97],
        [96,  6, 20, ..., 59,  6, 58],
        [96,  6, 20, ..., 43, 53, 73]], dtype=int64),
 array([[96,  6, 20, ..., 63, 33, 70],
        [96,  6, 20, ..., 33, 89, 36],
        [96,  6, 20, ..., 58, 28, 11],
        ...,
        [96,  6, 20, ..., 46, 28, 97],
        [96,  6, 20, ..., 59,  6, 58],
        [96,  6, 20, ..., 43, 53, 73]], dtype=int64)]

In [28]:
x1 = out[0]

In [29]:
x2 = out[1]

In [30]:
x1_slice = x1[:,:12]
x2_slice = x2[:,:12]

In [31]:
x1_slice

array([[87, 69, 42, ..., 67, 24, 21],
       [87, 69, 42, ..., 67, 24, 21],
       [87, 69, 42, ..., 67, 24, 21],
       ...,
       [87, 69, 42, ..., 67, 24, 21],
       [87, 69, 42, ..., 67, 24, 21],
       [87, 69, 42, ..., 67, 24, 21]], dtype=int64)

In [32]:
x2_slice

array([[87, 69, 42, ..., 67, 24, 21],
       [87, 69, 42, ..., 67, 24, 21],
       [87, 69, 42, ..., 67, 24, 21],
       ...,
       [87, 69, 42, ..., 67, 24, 21],
       [87, 69, 42, ..., 67, 24, 21],
       [87, 69, 42, ..., 67, 24, 21]], dtype=int64)

In [33]:
x2_slice == x1_slice

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])